youdu:
  # 管理员通知账号
#  admin: 李青峰
  admin: 马芸
  # 企业总机号码
  buin: 14434771
  # 有度服务器地址
  host: 172.168.1.251:7080
  # 企业应用AppId
  pId: ydF1609648834B43D79D89796A68C482F7
  # 企业应用的EncodingaesKey
  appAesKey: GEqkmDgGOJ0jlVkUZRf4FmPAp6TBcVulQVGSKTgwZfg=

server:
  port: 8082
spring:
  application:
    name: AozMeeti
  datasource:
      url: jdbc:mysql://meet.aoz.com:3306/aoz_meeting?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: aoz_meeting
      password: aoz_meeting
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 初始化时建立物理连接的个数
        initial-size: 5
        # 连接池的最小空闲数量
        min-idle: 5
        # 连接池最大连接数量
        max-active: 20
        # 获取连接时最大等待时间，单位毫秒
        max-wait: 60000
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 既作为检测的间隔时间又作为testWhileIdel执行的依据
        time-between-eviction-runs-millis: 60000
        # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
        min-evictable-idle-time-millis: 30000
        # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
        validation-query: select 'x'
        # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-borrow: false
        # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-return: false
        # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
        pool-prepared-statements: false
        # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
        filters: stat,wall,slf4j
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aoz:
  avatarPath: /JavaProject/meeting/img/
